spring:
  application:
    name: java-vault-connect-test
  config:
    import: vault://secret/mysql
  cloud:
    vault:
      #      token: 'myroot'
      host: 'localhost'
      scheme: 'http'
      port: 8200
      app-role:
        role-id: d886a75a-c2ff-0e5e-acb0-4df537e9b73d
        secret-id: 41b86ec6-6c98-fea7-1b60-ef0d5bb58691
      #      kv:
      #        backend: 'secret'
      #        application-name: "secret_test"
      authentication: approle
  datasource:
    username: ${vault.user}
    password: ${vault.password}
    url: jdbc:mysql://127.0.0.1:3306/employees
    driver-class-name: com.mysql.cj.jdbc.Driver

