spring:
  application:
    name: java-vault-connect-test
  cloud:
    vault:
      #      token: '00000000000000000'
      host: 'localhost'
      scheme: 'http'
      app-role:
        role-id: 'f0f37297-5120-e0e3-ebe3-d3bc738d31e9'
        secret-id: 'ce508976-90fc-07e1-310c-2d22eea65697'
