spring:
  application:
    name: java-vault-connect-test
  config:
    import: vault://secret/mysql
  cloud:
    vault:
      #      token: 'myroot'
      host: 'localhost'
      scheme: 'http'
      port: 8200
      app-role:
        role-id: 'f0f37297-5120-e0e3-ebe3-d3bc738d31e9'
        secret-id: 'ce508976-90fc-07e1-310c-2d22eea65697'
      #      kv:
      #        backend: 'secret'
      #        application-name: "secret_test"
      authentication: approle
  datasource:
    username: ${vault.user}
    password: ${vault.password}
    url: jdbc:mysql://127.0.0.1:3306/employees
    driver-class-name: com.mysql.cj.jdbc.Driver

